# Generated by Django 4.1.1 on 2022-09-26 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rename_contacts_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactView',
        ),
    ]
